.code

  SEGMENTATION_readCs PROC
    MOV AX, CS
    RET
  SEGMENTATION_readCs ENDP

  SEGMENTATION_readSs PROC
    MOV AX, SS
    RET
  SEGMENTATION_readSs ENDP

  SEGMENTATION_readDs PROC
    MOV AX, DS
    RET
  SEGMENTATION_readDs ENDP

  SEGMENTATION_readEs PROC
    MOV AX, ES
    RET
  SEGMENTATION_readEs ENDP

  SEGMENTATION_readFs PROC
    MOV AX, FS
    RET
  SEGMENTATION_readFs ENDP

  SEGMENTATION_readGs PROC
    MOV AX, GS
    RET
  SEGMENTATION_readGs ENDP

  SEGMENTATION_readLdtr PROC
    SLDT AX
    RET
  SEGMENTATION_readLdtr ENDP

  SEGMENTATION_readTr PROC
    STR AX
    RET
  SEGMENTATION_readTr ENDP

END